remote_theme: "mmistakes/minimal-mistakes@4.28.0"
title: "SAP Stammtisch Dortmund"
description: "Infos rund um den SAP Stammtisch Dortmund"
plugins: [jekyll-include-cache]
url: "https://sapstammtisch.github.io"
base_url: "/Dortmund"
site.locale: "de-DE"
atom_feed:
  hide: true
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/groups/13062692/"
    - label: "WhatsApp"
      icon: "fab fa-fw fa-whatsapp"
      url: "https://chat.whatsapp.com/FMg3Yl1T6nr3j4caubd4E4"
    - label: "SAP Community"
      icon: "fa fa-solid fa-link"
      url: "https://community.sap.com/t5/dortmund/gh-p/dortmund"
